// <auto-generated />
namespace BitEng.Security.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MenuItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MenuItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201807130504543_MenuItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
