// <auto-generated />
namespace BitEng.Security.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Role_DisplayName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Role_DisplayName));
        
        string IMigrationMetadata.Id
        {
            get { return "201807130356281_Role_DisplayName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
