// <auto-generated />
namespace Furnies.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ConfiguracionSistema_NombreMostrar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfiguracionSistema_NombreMostrar));
        
        string IMigrationMetadata.Id
        {
            get { return "201807172112396_ConfiguracionSistema_NombreMostrar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
